version: '3.8'

services:
  # --- Mosquitto MQTT Broker ---
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: greeneye_mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped

  # --- InfluxDB Time-Series Database ---
  influxdb:
    image: influxdb:2.7.5
    container_name: greeneye_influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=greeneye_admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=kitel1976!
      - DOCKER_INFLUXDB_INIT_ORG=GreenEye
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=5be92638-5260-458c-8287-2ce175a387aa
    restart: unless-stopped

  # --- Redis Cache 서비스 정의 ---
  redis:
    image: redis:7.0.12-alpine
    container_name: greeneye_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass kitel1976!
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # --- Nginx Web Server / Reverse Proxy ---
  nginx:
    image: nginx:1.25.1-alpine
    container_name: greeneye_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./images:/app/images:ro
    depends_on:
      - influxdb
      - redis
      - mosquitto
      - greeneye_backend_app # Flask 앱 컨테이너가 시작된 후에 시작
    restart: unless-stopped

  # --- Flask Backend Application (컨테이너화) ---
  greeneye_backend_app:
    build: . # Dockerfile을 사용해서 현재 폴더에서 빌드
    container_name: greeneye_backend_app
    volumes:
      - .:/app # 프로젝트 코드 마운트 (개발 중에는 실시간 코드 변경 반영을 위해 필요)
      - ./images:/app/images # 이미지를 Flask 앱 컨테이너에서도 볼 수 있도록 마운트
    environment: # 환경 변수 전달 (컨테이너 내부에서 .env 파일을 읽지 못할 수 있으므로 직접 전달)
      - FLASK_SECRET_KEY=super_secret_key_for_dev # 실제 값으로 변경
      - MQTT_BROKER_HOST=mosquitto # Mosquitto 컨테이너 이름으로 접속
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=5be92638-5260-458c-8287-2ce175a387aa # 실제 값으로 변경
      - INFLUXDB_ORG=GreenEye
      - INFLUXDB_BUCKET=sensor_data
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=kitel1976! # 실제 값으로 변경
    depends_on:
      - influxdb
      - redis
      - mosquitto
    restart: unless-stopped


volumes:
  mosquitto_data:
  mosquitto_log:
  influxdb_data:
  redis_data: