version: '3.8'

services:
  # --- Mosquitto MQTT Broker ---
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: greeneye_mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped

  # --- InfluxDB ---
  influxdb:
    image: influxdb:2.7.5
    container_name: greeneye_influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=greeneye_admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=kitel1976!
      - DOCKER_INFLUXDB_INIT_ORG=GreenEye
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=5be92638-5260-458c-8287-2ce175a387aa
    restart: unless-stopped

  # --- Redis ---
  redis:
    image: redis:7.0.12-alpine
    container_name: greeneye_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass kitel1976!
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # --- Nginx (default.conf 방식) ---
  nginx:
    image: nginx:1.25.1-alpine
    container_name: greeneye_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./images:/app/images:ro
    depends_on:
      - influxdb
      - redis
      - mosquitto
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_log:
  influxdb_data:
  redis_data: