version: '3.8'

services:
  # 1. Flask 백엔드
  greeneye_backend_app:
    build: .
    container_name: greeneye_backend_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    command: >
      gunicorn --workers 1 --threads 4 --timeout 120
      -b 0.0.0.0:5000 app:app
    volumes:
      - .:/app
      - ./images:/app/images
      - ./greeneye_users.db:/app/greeneye_users.db
    env_file:
      - .env
    depends_on:
      mosquitto:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import socket; s=socket.socket(); s.connect((\"localhost\",5000)); s.close()'"]
      interval: 30s
      timeout: 5s
      retries: 3

  # 2. Nginx 리버스 프록시
  nginx:
    image: nginx:1.25.1-alpine
    container_name: greeneye_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./images:/app/images:ro
    depends_on:
      greeneye_backend_app:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nginx -t && wget -S --spider http://127.0.0.1/ 2>&1 | grep -qE 'HTTP/1\\.1 (200|404)'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # 3. Mosquitto MQTT
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: greeneye_mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto_config:/mosquitto/config
      - greeneye_backend_mosquitto_data:/mosquitto/data
      - greeneye_backend_mosquitto_log:/mosquitto/log
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL","mosquitto_sub -h localhost -t '$$SYS/#' -C 1 -W 5 -u ${MQTT_USERNAME} -P ${MQTT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 4. InfluxDB 2.x
  influxdb:
    image: influxdb:2.7.5
    container_name: greeneye_influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    env_file:
      - .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8086/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # 5. Redis
  redis:
    image: redis:7.0.12-alpine
    container_name: greeneye_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  greeneye_backend_mosquitto_data:
  greeneye_backend_mosquitto_log:
  influxdb_data:
  redis_data:
